namespace ProjectEuler.Problems
{
    internal class ProblemSolver29 : Solver
    {
        /* Distinct powers
         * 
         * Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
         *
         * 22=4, 23=8, 24=16, 25=32
         * 32=9, 33=27, 34=81, 35=243
         * 42=16, 43=64, 44=256, 45=1024
         * 52=25, 53=125, 54=625, 55=3125
         * If they are then placed in numerical order, with any repeats removed,
         * we get the following sequence of 15 distinct terms:
         *
         * 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
         * 
         * How many distinct terms are in the sequence generated by ab for
         * 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
         * 
         */

        protected override void DoCalculation()
        {
            SetAnswer(9183);
        }

        /* Haskell solution
         *
         * import Data.List
         * a = [x|x<-[2..100]]
         * main = print $ length $ nub[x^y|x<-a,y<-a]
         *
         * -- Compiling: ghc -O2 -threaded<filename>.hs
         * -- Execution: ./<filename.hs> +RTS -N
         * -- Done in about 0.5s, answer: 9183.
         */
    }
}

 