{-
Problem description - Triangular, pentagonal, and hexagonal
-----------------------------------------------------------
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.

Problem analysis
----------------
- 

Runtime information
-------------------
Compilation      ghc -O2 -threaded <filename>.hs
Execution        ./<filename> +RTS -N
                 for performance run output use: --output <filename>.html
Time             
Answer           
-}

import Data.List
-- import Criterion.Main

main :: IO()
main = print $ answer 2
-- main = defaultMain [bgroup "answer" [bench "default" $ whnf answer (9999,9)]]

answer :: Int -> [Int]
answer x = take x [n|n<-[1..],isElemOf n]

isElemOf :: Int -> Bool
isElemOf x = elem x (triangleNumbers `intersect` pentagonalNumbers `intersect` hexagonalNumbers)

triangleNumbers :: [Int]
triangleNumbers = [div (2*n+n) 2|n<-[1..300]]

pentagonalNumbers :: [Int]
pentagonalNumbers = [div (3*n*n-n) 2|n<-[1..300]]

hexagonalNumbers :: [Int]
hexagonalNumbers = [2*n*n-n|n<-[1..300]]